name: Send Message to Discord

on:
  issues:
    types: [opened]

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send message to Discord
        uses: actions/http-client@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          method: POST
          headers: |
            Content-Type: application/json
          data: |
            {
              "content": "${{ github.event.issue.title }}"
            }
