name: Send Message to Discord

on:
  issues:
    types: [opened]

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send message to Discord
        run: |
          MESSAGE="${{ github.event.issue.title }}"
          WEBHOOK_URL="${{ secrets.DISCORD_WEBHOOK_URL }}"
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"${MESSAGE}\"}" "$WEBHOOK_URL"
